// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqfignpoauuqngchuzkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxZmlnbnBvYXV1cW5nY2h1emt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4ODkwNTYsImV4cCI6MjA3MzQ2NTA1Nn0.27tnkbw2etqtS257IUGB_s2wjUi6grMJSu-k-rl4NQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});